package org.example.adapters.in.utils;
import java.util.HashMap;
import java.util.Map;
public class MapeoBanderasUtil {
    private static final Map<String, String> MAPA_CODIGO_BANDERA = new HashMap<>();
    private static final Map<String, String> MAPA_NOMBRE_MONEDA = new HashMap<>();
    static {
        MAPA_CODIGO_BANDERA.put("USD", "us");
        MAPA_CODIGO_BANDERA.put("AED", "ae");
        MAPA_CODIGO_BANDERA.put("AFN", "af");
        MAPA_CODIGO_BANDERA.put("ALL", "al");
        MAPA_CODIGO_BANDERA.put("AMD", "am");
        MAPA_CODIGO_BANDERA.put("ANG", "an");
        MAPA_CODIGO_BANDERA.put("AOA", "ao");
        MAPA_CODIGO_BANDERA.put("ARS", "ar");
        MAPA_CODIGO_BANDERA.put("AUD", "au");
        MAPA_CODIGO_BANDERA.put("AWG", "aw");
        MAPA_CODIGO_BANDERA.put("AZN", "az");
        MAPA_CODIGO_BANDERA.put("BAM", "ba");
        MAPA_CODIGO_BANDERA.put("BBD", "bb");
        MAPA_CODIGO_BANDERA.put("BDT", "bd");
        MAPA_CODIGO_BANDERA.put("BGN", "bg");
        MAPA_CODIGO_BANDERA.put("BHD", "bh");
        MAPA_CODIGO_BANDERA.put("BIF", "bi");
        MAPA_CODIGO_BANDERA.put("BMD", "bm");
        MAPA_CODIGO_BANDERA.put("BND", "bn");
        MAPA_CODIGO_BANDERA.put("BOB", "bo");
        MAPA_CODIGO_BANDERA.put("BRL", "br");
        MAPA_CODIGO_BANDERA.put("BSD", "bs");
        MAPA_CODIGO_BANDERA.put("BTN", "bt");
        MAPA_CODIGO_BANDERA.put("BWP", "bw");
        MAPA_CODIGO_BANDERA.put("BYN", "by");
        MAPA_CODIGO_BANDERA.put("BZD", "bz");
        MAPA_CODIGO_BANDERA.put("CAD", "ca");
        MAPA_CODIGO_BANDERA.put("CDF", "cd");
        MAPA_CODIGO_BANDERA.put("CHF", "ch");
        MAPA_CODIGO_BANDERA.put("CLF", "cl");
        MAPA_CODIGO_BANDERA.put("CLP", "cl");
        MAPA_CODIGO_BANDERA.put("CNH", "cn");
        MAPA_CODIGO_BANDERA.put("CNY", "cn");
        MAPA_CODIGO_BANDERA.put("COP", "co");
        MAPA_CODIGO_BANDERA.put("CRC", "cr");
        MAPA_CODIGO_BANDERA.put("CUP", "cu");
        MAPA_CODIGO_BANDERA.put("CVE", "cv");
        MAPA_CODIGO_BANDERA.put("CZK", "cz");
        MAPA_CODIGO_BANDERA.put("DJF", "dj");
        MAPA_CODIGO_BANDERA.put("DKK", "dk");
        MAPA_CODIGO_BANDERA.put("DOP", "do");
        MAPA_CODIGO_BANDERA.put("DZD", "dz");
        MAPA_CODIGO_BANDERA.put("EGP", "eg");
        MAPA_CODIGO_BANDERA.put("ERN", "er");
        MAPA_CODIGO_BANDERA.put("ETB", "et");
        MAPA_CODIGO_BANDERA.put("EUR", "eu");
        MAPA_CODIGO_BANDERA.put("FJD", "fj");
        MAPA_CODIGO_BANDERA.put("FKP", "fk");
        MAPA_CODIGO_BANDERA.put("FOK", "fo");
        MAPA_CODIGO_BANDERA.put("GBP", "gb");
        MAPA_CODIGO_BANDERA.put("GEL", "ge");
        MAPA_CODIGO_BANDERA.put("GGP", "gg");
        MAPA_CODIGO_BANDERA.put("GHS", "gh");
        MAPA_CODIGO_BANDERA.put("GIP", "gi");
        MAPA_CODIGO_BANDERA.put("GMD", "gm");
        MAPA_CODIGO_BANDERA.put("GNF", "gn");
        MAPA_CODIGO_BANDERA.put("GTQ", "gt");
        MAPA_CODIGO_BANDERA.put("GYD", "gy");
        MAPA_CODIGO_BANDERA.put("HKD", "hk");
        MAPA_CODIGO_BANDERA.put("HNL", "hn");
        MAPA_CODIGO_BANDERA.put("HRK", "hr");
        MAPA_CODIGO_BANDERA.put("HTG", "ht");
        MAPA_CODIGO_BANDERA.put("HUF", "hu");
        MAPA_CODIGO_BANDERA.put("IDR", "id");
        MAPA_CODIGO_BANDERA.put("ILS", "il");
        MAPA_CODIGO_BANDERA.put("IMP", "im");
        MAPA_CODIGO_BANDERA.put("INR", "in");
        MAPA_CODIGO_BANDERA.put("IQD", "iq");
        MAPA_CODIGO_BANDERA.put("IRR", "ir");
        MAPA_CODIGO_BANDERA.put("ISK", "is");
        MAPA_CODIGO_BANDERA.put("JEP", "je");
        MAPA_CODIGO_BANDERA.put("JMD", "jm");
        MAPA_CODIGO_BANDERA.put("JOD", "jo");
        MAPA_CODIGO_BANDERA.put("JPY", "jp");
        MAPA_CODIGO_BANDERA.put("KES", "ke");
        MAPA_CODIGO_BANDERA.put("KGS", "kg");
        MAPA_CODIGO_BANDERA.put("KHR", "kh");
        MAPA_CODIGO_BANDERA.put("KID", "ki");
        MAPA_CODIGO_BANDERA.put("KMF", "km");
        MAPA_CODIGO_BANDERA.put("KRW", "kr");
        MAPA_CODIGO_BANDERA.put("KWD", "kw");
        MAPA_CODIGO_BANDERA.put("KYD", "ky");
        MAPA_CODIGO_BANDERA.put("KZT", "kz");
        MAPA_CODIGO_BANDERA.put("LAK", "la");
        MAPA_CODIGO_BANDERA.put("LBP", "lb");
        MAPA_CODIGO_BANDERA.put("LKR", "lk");
        MAPA_CODIGO_BANDERA.put("LRD", "lr");
        MAPA_CODIGO_BANDERA.put("LSL", "ls");
        MAPA_CODIGO_BANDERA.put("LYD", "ly");
        MAPA_CODIGO_BANDERA.put("MAD", "ma");
        MAPA_CODIGO_BANDERA.put("MDL", "md");
        MAPA_CODIGO_BANDERA.put("MGA", "mg");
        MAPA_CODIGO_BANDERA.put("MKD", "mk");
        MAPA_CODIGO_BANDERA.put("MMK", "mm");
        MAPA_CODIGO_BANDERA.put("MNT", "mn");
        MAPA_CODIGO_BANDERA.put("MOP", "mo");
        MAPA_CODIGO_BANDERA.put("MRU", "mr");
        MAPA_CODIGO_BANDERA.put("MUR", "mu");
        MAPA_CODIGO_BANDERA.put("MVR", "mv");
        MAPA_CODIGO_BANDERA.put("MWK", "mw");
        MAPA_CODIGO_BANDERA.put("MXN", "mx");
        MAPA_CODIGO_BANDERA.put("MYR", "my");
        MAPA_CODIGO_BANDERA.put("MZN", "mz");
        MAPA_CODIGO_BANDERA.put("NAD", "na");
        MAPA_CODIGO_BANDERA.put("NGN", "ng");
        MAPA_CODIGO_BANDERA.put("NIO", "ni");
        MAPA_CODIGO_BANDERA.put("NOK", "no");
        MAPA_CODIGO_BANDERA.put("NPR", "np");
        MAPA_CODIGO_BANDERA.put("NZD", "nz");
        MAPA_CODIGO_BANDERA.put("OMR", "om");
        MAPA_CODIGO_BANDERA.put("PAB", "pa");
        MAPA_CODIGO_BANDERA.put("PEN", "pe");
        MAPA_CODIGO_BANDERA.put("PGK", "pg");
        MAPA_CODIGO_BANDERA.put("PHP", "ph");
        MAPA_CODIGO_BANDERA.put("PKR", "pk");
        MAPA_CODIGO_BANDERA.put("PLN", "pl");
        MAPA_CODIGO_BANDERA.put("PYG", "py");
        MAPA_CODIGO_BANDERA.put("QAR", "qa");
        MAPA_CODIGO_BANDERA.put("RON", "ro");
        MAPA_CODIGO_BANDERA.put("RSD", "rs");
        MAPA_CODIGO_BANDERA.put("RUB", "ru");
        MAPA_CODIGO_BANDERA.put("RWF", "rw");
        MAPA_CODIGO_BANDERA.put("SAR", "sa");
        MAPA_CODIGO_BANDERA.put("SBD", "sb");
        MAPA_CODIGO_BANDERA.put("SCR", "sc");
        MAPA_CODIGO_BANDERA.put("SDG", "sd");
        MAPA_CODIGO_BANDERA.put("SEK", "se");
        MAPA_CODIGO_BANDERA.put("SGD", "sg");
        MAPA_CODIGO_BANDERA.put("SHP", "sh");
        MAPA_CODIGO_BANDERA.put("SLE", "sl");
        MAPA_CODIGO_BANDERA.put("SLL", "sl");
        MAPA_CODIGO_BANDERA.put("SOS", "so");
        MAPA_CODIGO_BANDERA.put("SRD", "sr");
        MAPA_CODIGO_BANDERA.put("SSP", "ss");
        MAPA_CODIGO_BANDERA.put("STN", "st");
        MAPA_CODIGO_BANDERA.put("SYP", "sy");
        MAPA_CODIGO_BANDERA.put("SZL", "sz");
        MAPA_CODIGO_BANDERA.put("THB", "th");
        MAPA_CODIGO_BANDERA.put("TJS", "tj");
        MAPA_CODIGO_BANDERA.put("TMT", "tm");
        MAPA_CODIGO_BANDERA.put("TND", "tn");
        MAPA_CODIGO_BANDERA.put("TOP", "to");
        MAPA_CODIGO_BANDERA.put("TRY", "tr");
        MAPA_CODIGO_BANDERA.put("TTD", "tt");
        MAPA_CODIGO_BANDERA.put("TVD", "tv");
        MAPA_CODIGO_BANDERA.put("TWD", "tw");
        MAPA_CODIGO_BANDERA.put("TZS", "tz");
        MAPA_CODIGO_BANDERA.put("UAH", "ua");
        MAPA_CODIGO_BANDERA.put("UGX", "ug");
        MAPA_CODIGO_BANDERA.put("UYU", "uy");
        MAPA_CODIGO_BANDERA.put("UZS", "uz");
        MAPA_CODIGO_BANDERA.put("VES", "ve");
        MAPA_CODIGO_BANDERA.put("VND", "vn");
        MAPA_CODIGO_BANDERA.put("VUV", "vu");
        MAPA_CODIGO_BANDERA.put("WST", "ws");
        MAPA_CODIGO_BANDERA.put("XAF", "cm");
        MAPA_CODIGO_BANDERA.put("XCD", "ag");
        MAPA_CODIGO_BANDERA.put("XDR", "un");
        MAPA_CODIGO_BANDERA.put("XOF", "sn");
        MAPA_CODIGO_BANDERA.put("XPF", "pf");
        MAPA_CODIGO_BANDERA.put("YER", "ye");
        MAPA_CODIGO_BANDERA.put("ZAR", "za");
        MAPA_CODIGO_BANDERA.put("ZMW", "zm");
        MAPA_CODIGO_BANDERA.put("ZWL", "zw");
        MAPA_NOMBRE_MONEDA.put("USD", "Dólar Estadounidense");
        MAPA_NOMBRE_MONEDA.put("PEN", "Sol Peruano");
        MAPA_NOMBRE_MONEDA.put("EUR", "Euro");
        MAPA_NOMBRE_MONEDA.put("JPY", "Yen Japonés");
        MAPA_NOMBRE_MONEDA.put("MXN", "Peso Mexicano");
        MAPA_NOMBRE_MONEDA.put("BRL", "Real Brasileño");
        MAPA_NOMBRE_MONEDA.put("COP", "Peso Colombiano");
        MAPA_NOMBRE_MONEDA.put("ARS", "Peso Argentino");
        MAPA_NOMBRE_MONEDA.put("AED", "Dírham EAU");
        MAPA_NOMBRE_MONEDA.put("AFN", "Afgani Afgano");
        MAPA_NOMBRE_MONEDA.put("ALL", "Lek Albanés");
        MAPA_NOMBRE_MONEDA.put("CAD", "Dólar Canadiense");
        MAPA_NOMBRE_MONEDA.put("CNY", "Yuan Chino");
        MAPA_NOMBRE_MONEDA.put("GBP", "Libra Esterlina");
    }
    public static String getCodigoBandera(String codigoMoneda) {
        return MAPA_CODIGO_BANDERA.get(codigoMoneda); // Devuelve null si no lo encuentra
    }
    public static String getNombreMoneda(String codigoMoneda) {
        return MAPA_NOMBRE_MONEDA.getOrDefault(codigoMoneda, codigoMoneda);
    }
}